### ISSUE TITLE
Desafío

### ISSUE THREAD

**Issue by pablojp** [NatashaRios/Courflix-react#1]
Hola Natasha! estuve revisando tus proyectos en github, entiendo que sos nueva en el mundo del desarrollo y el frontend.
Te propongo implementar mejoras en este proyecto como la implementación de hooks, tests funcionales, una api BFF, etc.
O si no es este proyecto tratá de mejorar algún otro donde semana a semana vayas metiendo mejoras y te sirve para ir aprendiendo, y lo usas como proyecto referente donde expongas tus conocimientos.

Saludos!!

**Comment by NatashaRios** [comment]
Hola Pablo, cómo estás?
Antes que nada muchas gracias por los consejos y por tomarte el tiempo en escribirme!
Si, debería actualizarlo jaja ese fue el tp final del curso de Frontend inicial que hice donde React vimos el último mes con clases y lo básico y ahora la semana que viene termino el avanzado donde vimos todo lo que me nombraste, inclusive el tp final es mucho más complejo que este y estoy haciendo eso jaja también mi portfolio está hecho con next y hooks, no sé si viste mi github desde ahí o no, pero por las dudas te lo dejo y bienvenida las críticas (el repo en github lo tengo en privado): https://natasharios.com.ar
Y justo la semana que viene termino el avanzado y empiezo uno de backend jaja pero cuando esté más tranquila con los cursos voy a aprovechar para actualizar los proyectos!
Muchas gracias!

Natasha Rios

Natasha Rios

________________________________
De: Pablo Peralta <notifications@github.com>
Enviado: Wednesday, November 11, 2020 12:07:45 PM
Para: NatashaRios/Courflix-react <Courflix-react@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Asunto: [NatashaRios/Courflix-react] Desafío (#1)


Hola Natasha! estuve revisando tus proyectos en github, entiendo que sos nueva en el mundo del desarrollo y el frontend.
Te propongo implementar mejoras en este proyecto como la implementación de hooks, tests funcionales, una api BFF, etc.
O si no es este proyecto tratá de mejorar algún otro donde semana a semana vayas metiendo mejoras y te sirve para ir aprendiendo, y lo usas como proyecto referente donde expongas tus conocimientos.

Saludos!!

**Comment by pablojp** [comment]
Excelente entonces Natasha. Desde Mercado Libre estamos en busqueda constante de talentos, hay muchas oportunidades para perfiles tanto nuevos como con experiencia. Cuando te sientas mas cómoda en tiempos pasado los cursos, podemos seguir en contacto y si alguno de tus compañeros también está interesado podemos considerarlos para una futura entrevista. 

Saludos y seguí capacitandote, que de este mundo ya no tenés retorno seguramente :P

**Comment by NatashaRios** [comment]
Muchas gracias! Justo la otra vez estaba diciendo que tengo ganas de trabajar en Mercado Libre jajaja y no, de este mundo no me voy más, me encanta jajaja

Saludos,
Natasha Rios
________________________________
De: Pablo Peralta <notifications@github.com>
Enviado: jueves, 12 de noviembre de 2020 21:11
Para: NatashaRios/Courflix-react <Courflix-react@noreply.github.com>
Cc: Natasha Rios <natu.rios@hotmail.com>; Comment <comment@noreply.github.com>
Asunto: Re: [NatashaRios/Courflix-react] Desafío (#1)


Excelente entonces Natasha. Desde Mercado Libre estamos en busqueda constante de talentos, hay muchas oportunidades para perfiles tanto nuevos como con experiencia. Cuando te sientas mas cómoda en tiempos pasado los cursos, podemos seguir en contacto y si alguno de tus compañeros también está interesado podemos considerarlos para una futura entrevista.

Saludos y seguí capacitandote, que de este mundo ya no tenés retorno seguramente :P
